export const UnidadeHistoryAction = {
  NEGOTIATION_STARTED: "NEGOTIATION_STARTED",
  NEGOTIATION_CANCELLED: "NEGOTIATION_CANCELLED",
  QUEUE_PROMOTED: "QUEUE_PROMOTED",
  RESERVATION_ACTIVATED: "RESERVATION_ACTIVATED",
  RESERVATION_CANCELLED: "RESERVATION_CANCELLED",
  RESERVATION_EXPIRED: "RESERVATION_EXPIRED",
  SALE_CREATED: "SALE_CREATED",
} as const;

export type UnidadeHistoryAction =
  (typeof UnidadeHistoryAction)[keyof typeof UnidadeHistoryAction];
