export const NegotiationHistoryAction = {
  NEGOTIATION_CREATED: "NEGOTIATION_CREATED",
  NEGOTIATION_STARTED: "NEGOTIATION_STARTED",
  NEGOTIATION_CANCELLED: "NEGOTIATION_CANCELLED",
  // Fase A do Funil: estágio recalculado automaticamente pelos repositórios a
  // partir dos filhos (deriveNegotiationStage). Ação de sistema (performed_by null).
  NEGOTIATION_STAGE_CHANGED: "NEGOTIATION_STAGE_CHANGED",
  PROPOSAL_CREATED: "PROPOSAL_CREATED",
  PROPOSAL_SENT: "PROPOSAL_SENT",
  PROPOSAL_UNDER_ANALYSIS: "PROPOSAL_UNDER_ANALYSIS",
  PROPOSAL_ACCEPTED: "PROPOSAL_ACCEPTED",
  PROPOSAL_REJECTED: "PROPOSAL_REJECTED",
  QUEUE_ENTERED: "QUEUE_ENTERED",
  QUEUE_PROMOTED: "QUEUE_PROMOTED",
  RESERVATION_REQUESTED: "RESERVATION_REQUESTED",
  RESERVATION_APPROVED: "RESERVATION_APPROVED",
  RESERVATION_REJECTED: "RESERVATION_REJECTED",
  RESERVATION_CANCELLED: "RESERVATION_CANCELLED",
  RESERVATION_EXPIRED: "RESERVATION_EXPIRED",
  SALE_CREATED: "SALE_CREATED",
  RESERVATION_CONVERTED: "RESERVATION_CONVERTED",
  SALE_ADVANCED: "SALE_ADVANCED",
  SALE_COMPLETED: "SALE_COMPLETED",
  SALE_CANCELLED: "SALE_CANCELLED",
} as const;

export type NegotiationHistoryAction =
  (typeof NegotiationHistoryAction)[keyof typeof NegotiationHistoryAction];
