export type DevelopmentSettings = {
  developmentId: string;
  accountId: string;
  reservationDurationHours: number | null;
  requireAcceptedProposalForReservationRequest: boolean | null;
  requireCompleteClientDataForReservationRequest: boolean | null;
  queueEnabled: boolean | null;
  updatedAt: Date;
  // Simulador comercial
  entradaMinimaPct: number;
  entradaMaximaPct: number;
  entradaParceladaPermitida: boolean;
  entradaParceladaMaxVezes: number;
  parcelasMinimas: number;
  parcelasMaximas: number;
  indicePreEntrega: string;
  indicePosEntrega: string;
  dataEntregaEmpreendimento: string | null;
  carenciaMaximaMeses: number;
  aceitaBalao: boolean;
  balaoMaxQuantidade: number;
  aceitaPermuta: boolean;
  permutaTipos: string[];
  permutaValorMaximoPct: number;
  descontoMaximoPct: number;
  comissaoCorretorPct: number;
  tipoSaldo: "parcelas_incorporadora" | "financiamento_bancario" | "saldo_entrega";
  textoSaldoPersonalizado: string | null;
  logoEmpreendimentoUrl: string | null;
  logoLightUrl: string | null;
  logoDarkUrl: string | null;
  imagemCapaUrl: string | null;
  corEmpreendimento: string | null;
  usarLogoEmpreendimentoNoPdf: boolean;
  usarCorEmpreendimentoNoPdf: boolean;
  incluirFotoCapaNoPdf: boolean;
  aceitaSaldoEntrega: boolean;
  saldoEntregaMaxPct: number;
  textoSaldoEntrega: string | null;
  labelAgrupamento: string;
  labelUnidade: string;
  labelArea: string;
  mapaUrl: string | null;
  mapaConfigurado: boolean;
  // PDF texts
  pdfTitulo: string | null;
  pdfBullet1: string | null;
  pdfBullet2: string | null;
  pdfBullet3: string | null;
  pdfDisclaimer: string | null;
  pdfFraseRodape: string | null;
  pdfValidadeHoras: number;
  pdfTextoParcelamento: string | null;
  balaoPeriodicidade: string;
};
